////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by XCTools.
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
using XComponent.HelloWorld.Common;
using XComponent.Runtime.StateMachine.Factory;
using XComponent.Runtime.StateMachine.Pool;

namespace XComponent.HelloWorld.StateMachine
{
    public class HelloWorldStateMachineFactory : IStateMachineFactory
    {
        public IStateMachinePool GetStateMachinePool(int stateMachineCode)
        {
			IStateMachinePool stateMachinePool;
			switch((StdEnum)stateMachineCode)
			{
				case StdEnum.HelloWorld:
					stateMachinePool = new HelloWorldPool();
					break;
				case StdEnum.ResponseListener:
					stateMachinePool = new ResponseListenerPool();
					break;
				case StdEnum.HelloWorldResponse:
					stateMachinePool = new HelloWorldResponsePool();
					break;
                default:
			        stateMachinePool = null;
			        break;
			}

			return stateMachinePool;
        }
    }
}