language: csharp
branches:
  only:
  - master
script:
- "./build.sh -t All"
notifications:
  slack:
    secure: GeRB2jkWK2aIZxfK/1eqUkeIj6stsM6xTC9Hw15bHWOgQZN7vvq6yQZU+OezT/VK1PoUaDYJ0CbSjEan3yeqTp3zhkynHDpAM/1rz5LggJo9Mctp0g52Xtj92CKoiXl0TrmffAjDRThCTkct+fEsPq0qHoTtEcFvzBzXrbITZzYnuz1+WFYxUdWzbi9bSyakw6wkf2tdunNqmUGErKP7nFsUUYVJ398WKkftqVRRupiqN3m5sb0Ud1NtH/pgVFGfONqJWhYK2jQ2ZNmsZTd1ax+0N4O4+ZA3FI30upVuJaDZwXP2AODD6JkFdV11y44jLfC0y1dWu7rXETI37zUYbMCts/F3q3n8Bp2ypjUZ1YkO5lD+f8EGbsMLOD6gwWhRJ52CTGtkuOrO7aCnsGDdFoZ9CylL0pg/V1Ka/7dxQMyaLZnyhNBKIruK2x6dGfjB7L8FwaOBh2mTKj2wpSMfefK1xpyP7MB6EgFh277n9BFusiY+uNz/Io8u9TeIOxAeCjdZV0QIv/L8DUahoA1nt9hoVB7G62MQ+WWel6Tr8WGxRj7z3KBfj53YaW/ZVQaMdxRsWtThvpv2cgU1OpzMbGenQgEgcXptcd9r5QUvIb4bf10P2k9oC0WEYIvU7hmMb+2uQgukALpmQHZeQsaPYei+c8Qaey9OHPe/9SSYdQM=
