////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by XCTools.
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using XComponent.Runtime.Processing;
using XComponent.Runtime.Processing.HashCode;
using XComponent.Runtime.StateMachine.Actor.Messages;
using XComponent.HelloWorld.Common;
using XComponent.HelloWorld.StateMachine;
using XComponent.HelloWorld.Common.EventHashCodeCalculator;

namespace XComponent.HelloWorld.StateMachine
{
    public class BootStrapperHelper
    {
        public static string DeploymentPath { get; set; }
        
        public static IEnumerable<StateMachineExecution> GetStateMachineExecutionList()
        {
            var executionConfigList = new List<StateMachineExecution>();
            var factory = new HelloWorldStateMachineFactory();
            executionConfigList.Add(new StateMachineExecution((int)StdEnum.HelloWorld, ComponentHelper.COMPONENT_CODE, null, factory, false));
            executionConfigList.Add(new StateMachineExecution((int)StdEnum.ResponseListener, ComponentHelper.COMPONENT_CODE, null, factory, false));
            executionConfigList.Add(new StateMachineExecution((int)StdEnum.HelloWorldResponse, ComponentHelper.COMPONENT_CODE, null, factory, false));
            return executionConfigList;
        }
        
        public static IDictionary<int, IEventHashCodeCalculatorRepository> GetEventHashCodeCalculatorRepositories()
        {
            var eventHashCodeCalculatorRepositories = new Dictionary<int, IEventHashCodeCalculatorRepository>();
            eventHashCodeCalculatorRepositories.Add((int)StdEnum.HelloWorld, new HelloWorldEventHashCodeCalculatorRepository());
            eventHashCodeCalculatorRepositories.Add((int)StdEnum.ResponseListener, new ResponseListenerEventHashCodeCalculatorRepository());
            eventHashCodeCalculatorRepositories.Add((int)StdEnum.HelloWorldResponse, new HelloWorldResponseEventHashCodeCalculatorRepository());
            return eventHashCodeCalculatorRepositories;
        }
        
        public static IEnumerable<ComponentErrorExecution> GetComponentErrorExecutionList()
        {
            var errorConfigList = new List<ComponentErrorExecution>();
            errorConfigList.Add(new ComponentErrorExecution(ComponentHelper.COMPONENT_CODE, null));
            return errorConfigList;
        }
        
		public static CreateInstance GetCreateEntryPointMessage()
        {
			return new CreateInstance(ComponentHelper.COMPONENT_CODE, "HelloWorld", (int)StdEnum.HelloWorld, 0, "EntryPoint", null, -1, -1, null, null, false, new IncomingEvent() { Message = new XComponent.Common.Event.DefaultEvent() });
        }
    }
}
