//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.HelloWorld.Common
{
    public enum HelloWorldStateEnum
    {
		EntryPoint = 0,
		FatalError = -2147483648,
		Listening = 1,
    }
}