//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

namespace XComponent.HelloWorld.Common
{
    public enum StdEnum
    {
		HelloWorld = -69981087,
		HelloWorldResponse = -343862282,
		ResponseListener = -1152526010,
    }
}