//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.Common.ApiContext;
using XComponent.Runtime.Communication;
using XComponent.HelloWorld.Common;

namespace XComponent.HelloWorld.Common.Senders
{
    public interface IInitDefaultEventOnListeningHelloWorldSenderInterface
    {
		void CreateListener(RuntimeContext context, string privateTopic = null);


		void CreateListener(RuntimeContext context, XComponent.HelloWorld.UserObject.CreateListener transitionEvent, string privateTopic = null);


		void SendEvent(XComponent.HelloWorld.UserObject.CreateListener evt, string privateTopic = null);

		void SendEvent(StdEnum stdEnum, XComponent.HelloWorld.UserObject.CreateListener evt, string privateTopic = null);

    }

    public interface ICountHelloWorldResponseOnUpResponseListenerSenderInterface
    {


    }

    public interface ICreateListenerCreateListenerOnUpResponseListenerSenderInterface
    {


    }

    public interface IPingPingOnPublishedHelloWorldResponseSenderInterface
    {
		void Kill(RuntimeContext context);


		void Kill(RuntimeContext context, XComponent.HelloWorld.UserObject.Kill transitionEvent);


		void SendEvent(XComponent.HelloWorld.UserObject.Kill evt);

		void SendEvent(StdEnum stdEnum, XComponent.HelloWorld.UserObject.Kill evt);

    }

    public interface ISayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSenderInterface
    {
		void Kill(RuntimeContext context);


		void Kill(RuntimeContext context, XComponent.HelloWorld.UserObject.Kill transitionEvent);


		void SendEvent(XComponent.HelloWorld.UserObject.Kill evt);

		void SendEvent(StdEnum stdEnum, XComponent.HelloWorld.UserObject.Kill evt);

    }

    public interface ISayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSenderInterface
    {
		void Kill(RuntimeContext context);


		void Kill(RuntimeContext context, XComponent.HelloWorld.UserObject.Kill transitionEvent);


		void SendEvent(XComponent.HelloWorld.UserObject.Kill evt);

		void SendEvent(StdEnum stdEnum, XComponent.HelloWorld.UserObject.Kill evt);

    }

    public interface ISayHelloSayHelloOnPublishedHelloWorldResponseSenderInterface
    {
		void Kill(RuntimeContext context);


		void Kill(RuntimeContext context, XComponent.HelloWorld.UserObject.Kill transitionEvent);


		void SendEvent(XComponent.HelloWorld.UserObject.Kill evt);

		void SendEvent(StdEnum stdEnum, XComponent.HelloWorld.UserObject.Kill evt);

    }

    public interface IEntryPointSenderInterface
    {


    }

}