//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by XCTools.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using XComponent.HelloWorld.Common;

namespace XComponent.HelloWorld.Common.Senders
{
    public class SenderManager
    {
		private static InitDefaultEventOnListeningHelloWorldSender _initDefaultEventOnListeningHelloWorldSender;
		private static CountHelloWorldResponseOnUpResponseListenerSender _countHelloWorldResponseOnUpResponseListenerSender;
		private static CreateListenerCreateListenerOnUpResponseListenerSender _createListenerCreateListenerOnUpResponseListenerSender;
		private static PingPingOnPublishedHelloWorldResponseSender _pingPingOnPublishedHelloWorldResponseSender;
		private static SayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender _sayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender;
		private static SayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender _sayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender;
		private static SayHelloSayHelloOnPublishedHelloWorldResponseSender _sayHelloSayHelloOnPublishedHelloWorldResponseSender;
		private static EntryPointSender _EntryPointSender;

        public static InitDefaultEventOnListeningHelloWorldSender InitDefaultEventOnListeningHelloWorldSender
        {
            get
            {
                return _initDefaultEventOnListeningHelloWorldSender ??
                       (_initDefaultEventOnListeningHelloWorldSender = new InitDefaultEventOnListeningHelloWorldSender());
            }
        }

        public static CountHelloWorldResponseOnUpResponseListenerSender CountHelloWorldResponseOnUpResponseListenerSender
        {
            get
            {
                return _countHelloWorldResponseOnUpResponseListenerSender ??
                       (_countHelloWorldResponseOnUpResponseListenerSender = new CountHelloWorldResponseOnUpResponseListenerSender());
            }
        }

        public static CreateListenerCreateListenerOnUpResponseListenerSender CreateListenerCreateListenerOnUpResponseListenerSender
        {
            get
            {
                return _createListenerCreateListenerOnUpResponseListenerSender ??
                       (_createListenerCreateListenerOnUpResponseListenerSender = new CreateListenerCreateListenerOnUpResponseListenerSender());
            }
        }

        public static PingPingOnPublishedHelloWorldResponseSender PingPingOnPublishedHelloWorldResponseSender
        {
            get
            {
                return _pingPingOnPublishedHelloWorldResponseSender ??
                       (_pingPingOnPublishedHelloWorldResponseSender = new PingPingOnPublishedHelloWorldResponseSender());
            }
        }

        public static SayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender SayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender
        {
            get
            {
                return _sayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender ??
                       (_sayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender = new SayGoodbyeSayGoodbyeOnPublishedHelloWorldResponseSender());
            }
        }

        public static SayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender SayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender
        {
            get
            {
                return _sayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender ??
                       (_sayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender = new SayGoodbyeToAllSayGoodbyeToAllOnPublishedHelloWorldResponseSender());
            }
        }

        public static SayHelloSayHelloOnPublishedHelloWorldResponseSender SayHelloSayHelloOnPublishedHelloWorldResponseSender
        {
            get
            {
                return _sayHelloSayHelloOnPublishedHelloWorldResponseSender ??
                       (_sayHelloSayHelloOnPublishedHelloWorldResponseSender = new SayHelloSayHelloOnPublishedHelloWorldResponseSender());
            }
        }

        public static EntryPointSender EntryPointSender
        {
            get
            {
                return _EntryPointSender ??
                       (_EntryPointSender = new EntryPointSender());
            }
        }

    }
}
