version: 2
references:
  restore_repo: &restore_repo
    restore_cache:
      name: Restore checked out code
      keys:
        - v2-reactivexcomponent-net-repo-{{ .Branch }}-{{ .Revision }}
        - v2-reactivexcomponent-net-repo-{{ .Branch }}-
        - v2-reactivexcomponent-net-repo-

  restore_nuget: &restore_nuget
    restore_cache:
      name: Restore nuget cache
      keys:
        - v2-nuget-{{ .Branch }}-{{ checksum "shasum.tmp" }}
        - v2-nuget-{{ .Branch }}-
        - v2-nuget-

  generate_nuget_shasum: &generate_nuget_shasum
    run:
      name: Generate cache shasum
      command: find . -name "*.csproj" -exec shasum {} \+ | sort -n > shasum.tmp

  save_nuget: &save_nuget
    save_cache:
      name: Save nuget cache
      key: v2-nuget-{{ .Branch }}-{{ checksum "shasum.tmp" }}
      paths:
          - /home/circleci/.nuget
 
jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.12
    steps:
      - checkout
      - save_cache:
          key: v2-reactivexcomponent-net-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build_reactiveapi:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - *restore_repo
      - *generate_nuget_shasum
      - *restore_nuget
      - run:
          name: ReactiveApi - Build All
          command: |
            if [ "${CIRCLE_TAG}" == "" ]; then
              cd /home/circleci/project/ && ./build.sh -t All
            else
              cd /home/circleci/project/ && ./build.sh -t All -buildConfiguration=Release -buildVersion=$CIRCLE_TAG
            fi
      - *save_nuget
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - packaging
            - nuget

  build_integration_test:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - *restore_repo
      - *generate_nuget_shasum
      - *restore_nuget
      - run:
          name: Install Key for mono
          command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
      - run:
          name: Install mono 5.16.0.179
          command: echo "deb http://download.mono-project.com/repo/debian stable-stretch/snapshots/5.16.0.179 main" > /etc/apt/sources.list.d/mono-official-stable.list && apt-get update && apt-get install -y mono-devel
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: ReactiveApi - Build BuildIntegrationTests
          command: cd /home/circleci/project/ && ./build.sh -t BuildIntegrationTests
      - run:
          name: ReactiveApi - Build PackageDockerIntegrationTests
          command: cd /home/circleci/project/ && ./build.sh -t PackageDockerIntegrationTests
      - *save_nuget
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - docker
  
  run_reactiveapi_integration_test:
    docker:
      - image: circleci/node:10.12
    steps:
      - setup_remote_docker  
      - *restore_repo      
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Run docker compose for reactiveapi integration tests
          command: |
            cd ./docker/integration_tests/dockerScripts
            docker-compose -f ./docker-compose-reactiveapi.yml up --exit-code-from clientapp

  deploy_nuget:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - *restore_repo
      - *generate_nuget_shasum
      - *restore_nuget
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Deploy nuget package
          command: cd /home/circleci/project/ && ./build.sh -t PushPackage -buildConfiguration=Release -buildVersion=$CIRCLE_TAG -nugetkey=$NUGET_API_KEY
 
workflows:
  version: 2
  xcomponent_reactive_api:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /^[0-9]++\.[0-9]++\.[0-9]++/
            branches:
              only: /.*/
      - build_reactiveapi:
          requires:
          - checkout_code
          filters:
            tags:
              only: /^[0-9]++\.[0-9]++\.[0-9]++/
            branches:
              only: /.*/
      - build_integration_test:
          requires:
          - build_reactiveapi
          filters:
            tags:
              only: /^[0-9]++\.[0-9]++\.[0-9]++/
            branches:
              only: /.*/
      - run_reactiveapi_integration_test:
          requires:
          - build_integration_test
          filters:
            tags:
              only: /^[0-9]++\.[0-9]++\.[0-9]++/
            branches:
              only: /.*/
      - deploy_nuget:
          requires:
          - run_reactiveapi_integration_test
          filters:
            tags:
              only: /^[0-9]++\.[0-9]++\.[0-9]++/
            branches:
              ignore: /.*/
