version: 2
references:
  restore_repo: &restore_repo
    restore_cache:
      name: Restore checked out code
      keys:
        - v1-reactivexcomponent-net-repo-{{ .Branch }}-{{ .Revision }}
        - v1-reactivexcomponent-net-repo-{{ .Branch }}-
        - v1-reactivexcomponent-net-repo-

  restore_nuget: &restore_nuget
    restore_cache:
      name: Restore nuget cache
      keys:
        - v1-nuget-{{ .Branch }}-{{ checksum "shasum.tmp" }}
        - v1-nuget-{{ .Branch }}-
        - v1-nuget-

  generate_nuget_shasum: &generate_nuget_shasum
    run:
      name: Generate cache shasum
      command: find . -name "packages.config" -exec shasum {} \+ | sort -n > shasum.tmp

  save_nuget: &save_nuget
    save_cache:
      name: Save nuget cache
      key: v1-nuget-{{ .Branch }}-{{ checksum "shasum.tmp" }}
      paths:
          - /home/circleci/.nuget

jobs:
  checkout_code:
    docker:
      - image: circleci/node:10.12
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-reactivexcomponent-net-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  build_sh_reactiveapi:
    docker:
      - image:  microsoft/dotnet:2.1-sdk
    steps:
      - *restore_repo
      - *generate_nuget_shasum
      - *restore_nuget
      - run:
          name: ReactiveApi - Build All
          command: ./build.sh -t All
      - run:
          name: ReactiveApi - Build BuildIntegrationTests
          command: ./build.sh -t BuildIntegrationTests
      - run:
          name: ReactiveApi - Build PackageDockerIntegrationTests
          command: ./build.sh -t PackageDockerIntegrationTests
      - *save_nuget
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - docker
  reactiveapi_integrationtests:
    docker:
      - image: circleci/node:10.12
    steps:
      - setup_remote_docker  
      - *restore_repo      
      - attach_workspace:
          at: /home/circleci/project
      - run:
          name: Run docker compose for reactiveapi integration tests
          command: |
            cd ./docker/integration_tests/dockerScripts
            docker-compose -f ./docker-compose-reactiveapi.yml up --exit-code-from clientapp

workflows:
  version: 2
  xcomponent_reactive_api:
    jobs:
      - checkout_code
      - build_sh_reactiveapi:
          requires:
          - checkout_code
      - reactiveapi_integrationtests:
          requires:
          - build_sh_reactiveapi