version: 2
jobs:
  checkout_code:
    docker:
      - image: xcomponent/mono-git:1.3.0
    steps:
      - checkout
      - run: ./build.sh -t All

workflows:
  version: 2
  xcomponent_runtime:
    jobs:
      - checkout_code